// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX2NeWG3tJxAxwlf9y7PW8v346hVMNOTw',
    appId: '1:65417761817:web:7be432a9b6d33236730688',
    messagingSenderId: '65417761817',
    projectId: 'zivo-fbdee',
    authDomain: 'zivo-fbdee.firebaseapp.com',
    storageBucket: 'zivo-fbdee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOfscu4rlsZZRGGdK3PnnzfdFq9d10R8I',
    appId: '1:65417761817:android:bda1445784825fcf730688',
    messagingSenderId: '65417761817',
    projectId: 'zivo-fbdee',
    storageBucket: 'zivo-fbdee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoF7R1fK2Takhu91HohrcKc3A3f1GXZSA',
    appId: '1:65417761817:ios:7111c3b4062b11de730688',
    messagingSenderId: '65417761817',
    projectId: 'zivo-fbdee',
    storageBucket: 'zivo-fbdee.firebasestorage.app',
    iosClientId: '65417761817-a2ju5sm1fv4a2qiaobos5b0qhq70lasi.apps.googleusercontent.com',
    iosBundleId: 'com.example.zivo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoF7R1fK2Takhu91HohrcKc3A3f1GXZSA',
    appId: '1:65417761817:ios:7111c3b4062b11de730688',
    messagingSenderId: '65417761817',
    projectId: 'zivo-fbdee',
    storageBucket: 'zivo-fbdee.firebasestorage.app',
    iosClientId: '65417761817-a2ju5sm1fv4a2qiaobos5b0qhq70lasi.apps.googleusercontent.com',
    iosBundleId: 'com.example.zivo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX2NeWG3tJxAxwlf9y7PW8v346hVMNOTw',
    appId: '1:65417761817:web:b64edeeaaf401e1d730688',
    messagingSenderId: '65417761817',
    projectId: 'zivo-fbdee',
    authDomain: 'zivo-fbdee.firebaseapp.com',
    storageBucket: 'zivo-fbdee.firebasestorage.app',
  );
}
